import './globals.css'
import { Inter } from 'next/font/google'
import SelectLang from '/components/SelectLang';

import IntercomClientProvider from './IntercomClientProvider';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <IntercomClientProvider>
          <div><SelectLang /></div>
          {children}
        </IntercomClientProvider>
      </body>
    </html>
  )
}
